/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004e5f",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "background": "#0b1326",
        "surface-container-lowest": "#060e20",
        "surface-dim": "#0b1326",
        "surface-container-high": "#222a3d",
        "outline": "#859398",
        "on-secondary-container": "#00622e",
        "on-tertiary-container": "#415167",
        "on-surface-variant": "#bbc9cf",
        "surface-container-low": "#131b2e",
        "secondary-fixed-dim": "#00e475",
        "tertiary": "#cfe0fa",
        "on-primary-container": "#00586b",
        "inverse-primary": "#00677e",
        "inverse-surface": "#dae2fd",
        "on-surface": "#dae2fd",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#3c494e",
        "tertiary-container": "#b3c4de",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary-fixed": "#d3e4fe",
        "surface": "#0b1326",
        "on-primary": "#003642",
        "on-primary-fixed": "#001f27",
        "on-background": "#dae2fd",
        "secondary-fixed": "#62ff96",
        "surface-tint": "#3cd7ff",
        "on-secondary-fixed": "#00210b",
        "primary-container": "#00d4ff",
        "on-secondary-fixed-variant": "#005226",
        "secondary-container": "#05e777",
        "on-tertiary": "#213145",
        "on-secondary": "#003918",
        "on-error-container": "#ffdad6",
        "surface-container": "#171f33",
        "primary": "#a8e8ff",
        "primary-fixed-dim": "#3cd7ff",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary": "#7dffa2",
        "primary-fixed": "#b4ebff"
      },
      fontFamily: {
        headline: ["Roboto", "sans-serif"],
        body: ["Roboto", "sans-serif"],
        label: ["Roboto", "sans-serif"]
      }
    },
  },
  plugins: [],
}
